-- Seed data for The Flow (expression_events)
-- 50+ diverse, authentic expressions matching the RunExpression brand voice

-- Insert seed expressions with approved status
INSERT INTO public.expression_events (
  user_id,
  type,
  content,
  content_long,
  media_url,
  vibe_tags,
  moderation_status,
  visibility,
  metadata,
  created_at
) VALUES
-- Meditative, morning runs
(
  NULL,
  'text',
  'Today I ran for clarity. Left with anxiety, returned with acceptance.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Morning Miles', 'Peace'],
  'approved',
  'public',
  '{"mood": "calm", "source": "seed"}',
  NOW() - INTERVAL '2 days'
),
(
  NULL,
  'text',
  'First light. First step. First breath that actually felt like mine.',
  'Been running from myself for weeks. This morning, I finally stopped running away and just... ran.',
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Discovery'],
  'approved',
  'public',
  '{"mood": "peaceful", "source": "seed"}',
  NOW() - INTERVAL '3 days'
),
-- Crew energy, community
(
  NULL,
  'text',
  'The crew pulled me through miles 8-12. I showed up broken. They made me whole.',
  NULL,
  NULL,
  ARRAY['Grateful', 'Crew Energy', 'Flow State'],
  'approved',
  'public',
  '{"mood": "grateful", "source": "seed"}',
  NOW() - INTERVAL '1 day'
),
(
  NULL,
  'text',
  'Bacon tastes better when you earn it together.',
  'Sunday long run with the squad. 18 miles. 3 porta-potty stops. 1 epic breakfast after. This is why we run.',
  NULL,
  ARRAY['Celebratory', 'Crew Energy', 'Joy'],
  'approved',
  'public',
  '{"mood": "joyful", "source": "seed"}',
  NOW() - INTERVAL '5 days'
),
-- Struggle, suffering, growth
(
  NULL,
  'text',
  'Tempo run taught me I still have work to do. And that''s okay.',
  NULL,
  NULL,
  ARRAY['Defiant', 'Suffering', 'Late Night Flow'],
  'approved',
  'public',
  '{"mood": "determined", "source": "seed"}',
  NOW() - INTERVAL '4 hours'
),
(
  NULL,
  'text',
  'Every step hurt. Every step mattered.',
  'Comeback run after 2 weeks off with a cold. Body said no. Mind said go. We compromised at 5 miles of pure gratitude.',
  NULL,
  ARRAY['Injury Comeback', 'Struggle', 'Grateful'],
  'approved',
  'public',
  '{"mood": "grateful", "source": "seed"}',
  NOW() - INTERVAL '6 days'
),
-- Competitive, race day
(
  NULL,
  'text',
  'PR or ER. Went for the PR. Got humbled. Still worth it.',
  NULL,
  NULL,
  ARRAY['Competitive', 'Race Day', 'Suffering'],
  'approved',
  'public',
  '{"mood": "humbled", "source": "seed"}',
  NOW() - INTERVAL '7 days'
),
(
  NULL,
  'text',
  'Sub-40 10K! Three years of work in 39:47.',
  'Cried at the finish line. Not from pain. From proof that patience pays off.',
  NULL,
  ARRAY['Celebratory', 'Race Day', 'Triumph'],
  'approved',
  'public',
  '{"mood": "triumphant", "source": "seed"}',
  NOW() - INTERVAL '8 days'
),
-- Exploratory, new territory
(
  NULL,
  'text',
  'Found a new trail. Got lost for 45 minutes. Found myself instead.',
  NULL,
  NULL,
  ARRAY['Exploratory', 'New Territory', 'Discovery'],
  'approved',
  'public',
  '{"mood": "adventurous", "source": "seed"}',
  NOW() - INTERVAL '2 days'
),
(
  NULL,
  'text',
  'Ran a route I''ve never taken. Saw the city wake up. Remembered why I love this.',
  NULL,
  NULL,
  ARRAY['Exploratory', 'Morning Miles', 'Joy'],
  'approved',
  'public',
  '{"mood": "joyful", "source": "seed"}',
  NOW() - INTERVAL '10 hours'
),
-- Uncertain, processing
(
  NULL,
  'text',
  'Don''t know what I''m training for anymore. But I know I need to keep moving.',
  'Lost my race goal when the event got cancelled. But the miles still matter. Still searching for why.',
  NULL,
  ARRAY['Uncertain', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"mood": "contemplative", "source": "seed"}',
  NOW() - INTERVAL '12 hours'
),
-- More diverse expressions
(
  NULL,
  'text',
  'Recovery run = therapy session with better shoes.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '1 day'
),
(
  NULL,
  'text',
  'The hill doesn''t care about your excuses. Neither does growth.',
  NULL,
  NULL,
  ARRAY['Defiant', 'Suffering', 'Flow State'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '15 hours'
),
(
  NULL,
  'text',
  'Showed up. Laced up. That''s the win today.',
  'Didn''t feel like running. Did it anyway. 3 slow miles of resistance. Still counts.',
  NULL,
  ARRAY['Defiant', 'Solo Journey', 'Triumph'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '18 hours'
),
(
  NULL,
  'text',
  'Ran angry. Finished calm. The miles did their job.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '2 days'
),
(
  NULL,
  'text',
  '4AM. Dark. Cold. Perfect.',
  'Something about the pre-dawn miles hits different. The world is still asleep. I''m wide awake. This is mine.',
  NULL,
  ARRAY['Meditative', 'Morning Miles', 'Flow State'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '3 days'
),
(
  NULL,
  'text',
  'The treadmill is not the enemy. My ego is.',
  NULL,
  NULL,
  ARRAY['Defiant', 'Solo Journey', 'Discovery'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '5 hours'
),
(
  NULL,
  'text',
  'First run back after injury. Slow. Careful. Grateful for every pain-free step.',
  NULL,
  NULL,
  ARRAY['Injury Comeback', 'Grateful', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '4 days'
),
(
  NULL,
  'text',
  'The finish line is a lie. The process is the point.',
  'Marathon training week 12. Not worried about the race anymore. Just showing up for the work.',
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Flow State'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '20 hours'
),
(
  NULL,
  'text',
  'Ran with strangers. Finished as friends.',
  NULL,
  NULL,
  ARRAY['Celebratory', 'Crew Energy', 'Joy'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '6 days'
),
(
  NULL,
  'text',
  'Today''s mantra: one foot in front of the other. Repeat.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '8 hours'
),
(
  NULL,
  'text',
  'Negative split. Positive vibes. Perfect morning.',
  NULL,
  NULL,
  ARRAY['Celebratory', 'Morning Miles', 'Flow State'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '14 hours'
),
(
  NULL,
  'text',
  'The rain didn''t stop me. Neither did the doubt.',
  NULL,
  NULL,
  ARRAY['Defiant', 'Solo Journey', 'Triumph'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '1 day'
),
(
  NULL,
  'text',
  'Fartlek Friday with the crew. Laughed harder than I ran.',
  'Speed work shouldn''t be this fun but here we are. 8x400m of pure chaos and joy.',
  NULL,
  ARRAY['Celebratory', 'Crew Energy', 'Joy'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '2 days'
),
(
  NULL,
  'text',
  'Easy run. Easy mind. Hard to remember life before this rhythm.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '22 hours'
),
(
  NULL,
  'text',
  'Chasing sunrise. Caught perspective instead.',
  NULL,
  NULL,
  ARRAY['Exploratory', 'Morning Miles', 'Discovery'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '3 days'
),
(
  NULL,
  'text',
  'Miles 1-3: why am I doing this. Miles 4-6: oh that''s why.',
  NULL,
  NULL,
  ARRAY['Flow State', 'Solo Journey', 'Discovery'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '16 hours'
),
(
  NULL,
  'text',
  'Bonked at mile 10. The squad carried me home. Literally.',
  'Long runs are humbling. Good friends are everything. Grateful for both.',
  NULL,
  ARRAY['Grateful', 'Crew Energy', 'Struggle'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '5 days'
),
(
  NULL,
  'text',
  'New PR in the worst conditions. Proof that comfort zones are overrated.',
  NULL,
  NULL,
  ARRAY['Competitive', 'Race Day', 'Triumph'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '9 days'
),
(
  NULL,
  'text',
  'Ran to forget. Remembered everything. Made peace with it anyway.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '1 day'
),
(
  NULL,
  'text',
  'The track doesn''t lie. 12x400m at threshold. I''m getting stronger.',
  NULL,
  NULL,
  ARRAY['Competitive', 'Flow State', 'Triumph'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '4 days'
),
(
  NULL,
  'text',
  'Sunset run. Phone on airplane mode. Soul on full charge.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Late Night Flow', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '12 hours'
),
(
  NULL,
  'text',
  'They said 5:30AM was too early. They''re still asleep. I''m alive.',
  NULL,
  NULL,
  ARRAY['Defiant', 'Morning Miles', 'Flow State'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '7 hours'
),
(
  NULL,
  'text',
  'Today I ran for everyone who can''t. Grateful for these legs.',
  NULL,
  NULL,
  ARRAY['Grateful', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '2 days'
),
(
  NULL,
  'text',
  'Tempo run turned meditation. My breath, my metronome.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Flow State', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '19 hours'
),
(
  NULL,
  'text',
  'The comeback is always harder than the setback. Worth it.',
  'Six months off. Six weeks back. Still have a long way to go. But I''m going.',
  NULL,
  ARRAY['Injury Comeback', 'Defiant', 'Triumph'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '3 days'
),
(
  NULL,
  'text',
  'Ran the same loop. Found something new. That''s the magic.',
  NULL,
  NULL,
  ARRAY['Exploratory', 'Solo Journey', 'Discovery'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '1 day'
),
(
  NULL,
  'text',
  'Race pace felt easy today. Taper magic is real.',
  NULL,
  NULL,
  ARRAY['Competitive', 'Flow State', 'Joy'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '6 days'
),
(
  NULL,
  'text',
  'Ran through doubt. Ran through fear. Ran into confidence.',
  NULL,
  NULL,
  ARRAY['Defiant', 'Solo Journey', 'Triumph'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '13 hours'
),
(
  NULL,
  'text',
  'The miles don''t judge. They just witness.',
  'Bad day turned into good run. Not fixed. Just... lighter.',
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '4 days'
),
(
  NULL,
  'text',
  'Every runner has a story. Today I listened to mine.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Discovery'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '11 hours'
),
(
  NULL,
  'text',
  'The crew showed up in the rain. So did I. That''s love.',
  NULL,
  NULL,
  ARRAY['Grateful', 'Crew Energy', 'Joy'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '2 days'
),
(
  NULL,
  'text',
  'Strava said easy. Body said no. Mind said let''s negotiate.',
  'Settled on conversational pace. Sometimes the plan needs editing. That''s okay.',
  NULL,
  ARRAY['Uncertain', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '17 hours'
),
(
  NULL,
  'text',
  'Long run complete. Legs tired. Heart full.',
  NULL,
  NULL,
  ARRAY['Celebratory', 'Solo Journey', 'Joy'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '5 days'
),
(
  NULL,
  'text',
  'Ran to clear my head. Filled it with ideas instead. Happy accident.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Discovery'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '21 hours'
),
(
  NULL,
  'text',
  'The taper crazies are real. 3 easy miles felt like 13.',
  NULL,
  NULL,
  ARRAY['Uncertain', 'Solo Journey', 'Struggle'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '7 days'
),
(
  NULL,
  'text',
  'Recovery week. Learning that rest is training too.',
  NULL,
  NULL,
  ARRAY['Meditative', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '3 days'
),
(
  NULL,
  'text',
  'Ran the bridge. Conquered the fear. One step at a time.',
  'That hill used to own me. Today I owned it. Progress.',
  NULL,
  ARRAY['Defiant', 'New Territory', 'Triumph'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '1 day'
),
(
  NULL,
  'text',
  'Morning miles with coffee after. This is the routine.',
  NULL,
  NULL,
  ARRAY['Celebratory', 'Morning Miles', 'Joy'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '9 hours'
),
(
  NULL,
  'text',
  'Ran in new shoes. Felt like flying. PR imminent.',
  NULL,
  NULL,
  ARRAY['Celebratory', 'Flow State', 'Joy'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '23 hours'
),
(
  NULL,
  'text',
  'The run saved me today. No other way to say it.',
  'Showed up broken. Left whole. This is why we do this.',
  NULL,
  ARRAY['Grateful', 'Solo Journey', 'Peace'],
  'approved',
  'public',
  '{"source": "seed"}',
  NOW() - INTERVAL '6 days'
);
